### ISSUE TITLE
Error after npm run build.prod 

### ISSUE THREAD

**Issue by NathanielMalca** [mgechev/angular2-seed#607]
it seems that on build the the path is doubled like this several times PrizeManagement\components\PrizeManagement\components

of course this is not really the physical path so it's really strage .

the seed works great on npm start

after running npm run build.prod  . i get this error:

D:\wu\angular2-seed>npm run build.prod

> angular2-seed@0.0.0 build.prod D:\wu\angular2-seed
> gulp build.prod

[16:43:28] Requiring external module ts-node/register
[16:43:53] Loading tasks folder D:\wu\angular2-seed\tools\tasks\seed
[16:43:53] Registering task D:\wu\angular2-seed\tools\tasks\seed\build.assets.dev
[16:43:53] Registering task D:\wu\angular2-seed\tools\tasks\seed\build.assets.prod
[16:43:53] Registering task D:\wu\angular2-seed\tools\tasks\seed\build.bundles.app
[16:43:53] Registering task D:\wu\angular2-seed\tools\tasks\seed\build.bundles
[16:43:53] Registering task D:\wu\angular2-seed\tools\tasks\seed\build.docs
[16:43:53] Registering task D:\wu\angular2-seed\tools\tasks\seed\build.html_css.prod
[16:43:53] Registering task D:\wu\angular2-seed\tools\tasks\seed\build.index.dev
[16:43:53] Registering task D:\wu\angular2-seed\tools\tasks\seed\build.index.prod
[16:43:53] Registering task D:\wu\angular2-seed\tools\tasks\seed\build.js.dev
[16:43:53] Registering task D:\wu\angular2-seed\tools\tasks\seed\build.js.e2e
[16:43:53] Registering task D:\wu\angular2-seed\tools\tasks\seed\build.js.prod
[16:43:53] Registering task D:\wu\angular2-seed\tools\tasks\seed\build.js.test
[16:43:53] Registering task D:\wu\angular2-seed\tools\tasks\seed\build.js.tools
[16:43:53] Registering task D:\wu\angular2-seed\tools\tasks\seed\check.versions
[16:43:53] Registering task D:\wu\angular2-seed\tools\tasks\seed\clean.all
[16:43:53] Registering task D:\wu\angular2-seed\tools\tasks\seed\clean.dev
[16:43:53] Registering task D:\wu\angular2-seed\tools\tasks\seed\clean.prod
[16:43:53] Registering task D:\wu\angular2-seed\tools\tasks\seed\clean.tools
[16:43:53] Registering task D:\wu\angular2-seed\tools\tasks\seed\karma.start
[16:43:53] Registering task D:\wu\angular2-seed\tools\tasks\seed\serve.coverage
[16:43:53] Registering task D:\wu\angular2-seed\tools\tasks\seed\serve.docs
[16:43:53] Registering task D:\wu\angular2-seed\tools\tasks\seed\server.start
[16:43:53] Registering task D:\wu\angular2-seed\tools\tasks\seed\tslint
[16:43:53] Registering task D:\wu\angular2-seed\tools\tasks\seed\watch.dev
[16:43:53] Registering task D:\wu\angular2-seed\tools\tasks\seed\watch.e2e
[16:43:53] Registering task D:\wu\angular2-seed\tools\tasks\seed\watch.test
[16:43:53] Loading tasks folder D:\wu\angular2-seed\tools\tasks\project
[16:43:53] Registering task D:\wu\angular2-seed\tools\tasks\project\sample.task
[16:43:53] Using gulpfile D:\wu\angular2-seed\gulpfile.ts
[16:43:53] Starting 'build.prod'...
[16:43:53] Starting 'clean.prod'...
[16:43:54] Deleted D:\wu\angular2-seed\dist\prod, D:\wu\angular2-seed\dist\tmp
[16:43:54] Finished 'clean.prod' after 1 s
[16:43:54] Starting 'tslint'...
[16:43:59] Finished 'tslint' after 5.34 s
[16:43:59] Starting 'build.assets.prod'...
[16:44:00] Finished 'build.assets.prod' after 1.27 s
[16:44:00] Starting 'build.html_css.prod'...
[16:44:07] Finished 'build.html_css.prod' after 6.6 s
[16:44:07] Starting 'build.js.prod'...
[16:44:11] Plumber found unhandled error:
 Error in plugin 'gulp-inline-ng2-template'
Message:
    ENOENT: no such file or directory, open 'D:\wu\angular2-seed\src\Login\components\Login\components\login.component.html'
Details:
    errno: -4058
    code: ENOENT
    syscall: open
    path: D:\wu\angular2-seed\src\Login\components\Login\components\login.component.html
    fileName: D:\wu\angular2-seed\src\Login\components\login.component.ts
[16:44:11] Plumber found unhandled error:
 Error in plugin 'gulp-inline-ng2-template'
Message:
    ENOENT: no such file or directory, open 'D:\wu\angular2-seed\src\PrizeManagement\components\PrizeManagement\components\add-prize.component.html'
Details:
    errno: -4058
    code: ENOENT
    syscall: open
    path: D:\wu\angular2-seed\src\PrizeManagement\components\PrizeManagement\components\add-prize.component.html
    fileName: D:\wu\angular2-seed\src\PrizeManagement\components\add-prize.component.ts
[16:44:11] Plumber found unhandled error:
 Error in plugin 'gulp-inline-ng2-template'
Message:
    ENOENT: no such file or directory, open 'D:\wu\angular2-seed\src\PrizeManagement\components\PrizeManagement\components\add-surprize.component.html'
Details:
    errno: -4058
    code: ENOENT
    syscall: open
    path: D:\wu\angular2-seed\src\PrizeManagement\components\PrizeManagement\components\add-surprize.component.html
    fileName: D:\wu\angular2-seed\src\PrizeManagement\components\add-surprize.component.ts
[16:44:11] Plumber found unhandled error:
 Error in plugin 'gulp-inline-ng2-template'
Message:
    ENOENT: no such file or directory, open 'D:\wu\angular2-seed\src\PrizeManagement\components\PrizeManagement\components\prizes-table.component.html'
Details:
    errno: -4058
    code: ENOENT
    syscall: open
    path: D:\wu\angular2-seed\src\PrizeManagement\components\PrizeManagement\components\prizes-table.component.html
    fileName: D:\wu\angular2-seed\src\PrizeManagement\components\prizes-table.component.ts
[16:44:11] Plumber found unhandled error:
 Error in plugin 'gulp-inline-ng2-template'
Message:
    ENOENT: no such file or directory, open 'D:\wu\angular2-seed\src\UserManagement\components\userManagement\components\user-management.html'
Details:
    errno: -4058
    code: ENOENT
    syscall: open
    path: D:\wu\angular2-seed\src\UserManagement\components\userManagement\components\user-management.html
    fileName: D:\wu\angular2-seed\src\UserManagement\components\user-management.ts
[16:44:11] Plumber found unhandled error:
 Error in plugin 'gulp-inline-ng2-template'
Message:
    ENOENT: no such file or directory, open 'D:\wu\angular2-seed\src\UserManagement\components\userManagement\components\users-table.component.html'
Details:
    errno: -4058
    code: ENOENT
    syscall: open
    path: D:\wu\angular2-seed\src\UserManagement\components\userManagement\components\users-table.component.html
    fileName: D:\wu\angular2-seed\src\UserManagement\components\users-table.component.ts
D:/wu/angular2-seed/src/PrizeManagement/components/add-surprize.component.ts(74,10): error TS2339: Property 'surprizeRegistrationForm' does not exist on type 'AddSurprizeComponent'.
D:/wu/angular2-seed/src/PrizeManagement/components/add-surprize.component.ts(139,18): error TS2339: Property 'setErrors' does not exist on type 'NgForm'.
D:/wu/angular2-seed/src/PrizeManagement/components/add-surprize.component.ts(148,20): error TS2339: Property 'setErrors' does not exist on type 'NgForm'.
[16:44:13] TypeScript: 3 semantic errors
[16:44:13] TypeScript: emit succeeded (with errors)
[16:44:13] Finished 'build.js.prod' after 6.51 s
[16:44:13] Starting 'build.bundles'...
[16:44:24] Finished 'build.bundles' after 11 s
[16:44:24] Starting 'build.bundles.app'...
Unhandled rejection Error on fetch for dist/tmp/UserManagement/components/user-management.js at file:///D:/wu/angular2-seed/dist/tmp/UserManagement/components/user-management.js
        Loading dist/tmp/app/components/app.component.js
        Loading dist/tmp/main.js
        Error: ENOENT: no such file or directory, open 'D:\wu\angular2-seed\dist\tmp\UserManagement\components\user-management.js'
    at Error (native)

**Comment by mgechev** [comment]
@ludohenin would you take a look at this one and #610 when you have time?

**Comment by ludohenin** [comment]
@mgechev sure.

**Comment by TheDonDope** [comment]
@mgechev #610 is fixed by now :)

**Comment by d3viant0ne** [comment]
From what I can see, the aren't related. Normally things like "Error: ENOENT: no such file or directory" are a configuration problem.

**Comment by d3viant0ne** [comment]
Closing this for now. If your issue still exists, @ me and i'll reopen it.

**Comment by NathanielMalca** [comment]
Hey @d3viant0ne , @TheDonDope , @mgechev  I still see the problem going on .

Like before on npm start everything works fine , but again after nmp run build.prod something goes wrong .

I would highly appreciate help since i need the version for production purposes 

[18:07:45] Starting 'build.bundles.app'...
Unhandled rejection Error on fetch for dist/tmp/app/components/app.component.js at file:///C:/Users/WUDeveloper/WebstormProjects/seed-mgechev/angular2-seed/dist/tmp/app/components/app.component.js
        Loading dist/tmp/main.js
        Error: ENOENT: no such file or directory, open 'C:\Users\WUDeveloper\WebstormProjects\seed-mgechev\angular2-seed\dist\tmp\app\components\app.component.js'
    at Error (native)

![image](https://cloud.githubusercontent.com/assets/17062686/14085598/73c4d08c-f529-11e5-92a5-1c0ca950aa0f.png)

**Comment by hhsadiq** [comment]
I am getting the same error of file not found. Did anyone found a solution...??

**Comment by NathanielMalca** [comment]
well i found the problem and it should be fixed . 

I created a component with a templateUrl . 

now, if i only indicate the path as follows './my.component.html' the relative path won't word on npm start but it will work on npm run prod.build - meaning the path will be build correctly.

To being able to work with the component while using "npm start" i needed to indicate in the templateUrl the full path : './my/components/my.html' .

this is a serious :bug:  that forces me to change all the templateUrl's paths throughout the project when production version is needed (checked on windows 10, webstorm ).

**Comment by ludohenin** [comment]
@NathanielMalca if you want to use relative path you have to add `moduleId: module.id` to you component config object.

**Comment by mgechev** [comment]
@NathanielMalca @ludohenin is correct. On top of that, `module.id` is something which is not considered best practice since it is commonjs specific.

I'd recommend you to use absolute paths to your template until there's a standardized across module loaders mechanism for pointing to the current path (such `module.id` in cjs).

**Comment by lsim** [comment]
Got it - keep using absolute paths. Relative template paths are not exactly important to me. 

What to do about `gulp build.prod` (specifically `build.js.prod`), which acts very much like it expects relative paths in my template urls? Did I miss something in the above?

**Comment by mgechev** [comment]
If you want to use absolute paths for your templates and styles, then remove `module.id` from the `@Component` decorators.

**Comment by lsim** [comment]
Thanks for the insanely speedy reply (and an awesome seed) :)

I don't have any moduleId properties set on my `@Component` decorators. Project wide search turned out just one on my top level component (`app.component.ts`). Removing that one didn't fix the problem.

I still get stuff like

`[22:17:45] Starting 'build.js.prod'...
Error: ENOENT: no such file or directory, open '/Users/los/src/priv/mobro/dist/tmp/app/lookupgraph/app/lookupgraph/lookupgraph.component.html'`

**Comment by mgechev** [comment]
Thanks! I missed that `gulp-inline-ng2-templates` has a configuration option for the way it is supposed to resolve the templates. In `build.js.prod.ts`, `INLINE_OPTIONS` has a property `useRelativePaths: true`, most likely you'd want to redefine this task in `tools/project/build.js.prod.ts` and drop this configuration property.

**Comment by lsim** [comment]
That did it. You're awesome.
